### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by osmanorhan** [kellyselden/ember-i18n-csv#53] opened 2016-06-13 08:47 UTC
Hi,
https://github.com/kellyselden/ember-i18n-csv/blob/master/lib/to-csv.js#L77  there, when I get this line into try catch block, I got an error like that:
`[SyntaxError: Unexpected reserved word]`

Ember-i18n-csv installed as a global npm package and I use this command inside locales folder:
ember-i18n-csv to-csv --locales-path=./ --csv-path=i18n.csv

**Comment by kellyselden** [comment] 2016-06-14 03:07
dupe of #52

**Closed by kellyselden** 2016-06-14 03:07 UTC

**Comment by kellyselden** [comment] 2016-06-14 16:00
Please follow #52 for new developments.
